### ISSUE TITLE
POSSIBLY mounting volume to .:/home/rstudio.... if container doesnt break

### ISSUE THREAD

**Issue by xnrxng** [DSCI-310-2024/dsci-310_group-7_wine-quality-prediction#117]

**Comment by ricochn02** [comment]
I probably won't change the mounting location to avoid since it's a significant risky change right before our deadline. The rocker docs explicitly say that we shouldn't mount directly to home/rstudio anyway: https://rocker-project.org/images/versioned/rstudio.html#editing-work-on-rstudio-server
